### ISSUE TITLE
Accept URL encoded paths

### ISSUE THREAD

**Issue by Timendus** [nuts-foundation/nuts-crypto#12]
My client happens to treat parameters different from paths:

Create pubkey:

```json
{"time":"2019-12-12T15:28:42.9276069Z","id":"","remote_ip":"172.25.0.1","host":"localhost:21323","method":"POST","uri":"/crypto/generate?legalEntity=urn:oid:2.16.840.1.113883.2.4.6.1:12345678","user_agent":"axios/0.19.0","status":200,"error":"","latency":189594800,"latency_human":"189.5948ms","bytes_in":0,"bytes_out":451}
```

Get pubkey:
```json
{"time":"2019-12-12T15:28:42.9411355Z","id":"","remote_ip":"172.25.0.1","host":"localhost:21323","method":"GET","uri":"/crypto/public_key/urn%3Aoid%3A2.16.840.1.113883.2.4.6.1%3A12345678","user_agent":"axios/0.19.0","status":404,"error":"","latency":724600,"latency_human":"724.6µs","bytes_in":0,"bytes_out":0}
```

Note that `uri` is `/crypto/generate?legalEntity=urn:oid:2.16.840.1.113883.2.4.6.1:12345678` in the first case but `/crypto/public_key/urn%3Aoid%3A2.16.840.1.113883.2.4.6.1%3A12345678` in the second. The first call works, the second does not.

Of course, this is something that can be fixed on the client side, however for the sake of adoption it would be nice if it simply didn't matter.

**Comment by reinkrul** [comment]
What is the error you're encountering?

In the 'path' component of a URI colons ( : ) are allowed so they don't need to be encoded. I tested both variants (encoded and plain) and both work fine (run in IntelliJ):

```
POST http://localhost:1323/crypto/generate?legalEntity=urn:oid:2.16.840.1.113883.2.4.6.1:12345678

###

GET http://localhost:1323/crypto/public_key/urn%3Aoid%3A2.16.840.1.113883.2.4.6.1%3A12345678

###

GET http://localhost:1323/crypto/public_key/urn:oid:2.16.840.1.113883.2.4.6.1:12345678

###
```

```
Testing started at 11:26 ...

HTTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
Date: Thu, 27 Feb 2020 10:26:06 GMT
Content-Length: 451

> 2020-02-27T112606.200.txt

Response code: 200 (OK); Time: 112ms; Content length: 451 bytes
HTTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
Date: Thu, 27 Feb 2020 10:26:06 GMT
Content-Length: 451

> 2020-02-27T112606-1.200.txt

Response code: 200 (OK); Time: 57ms; Content length: 451 bytes
HTTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
Date: Thu, 27 Feb 2020 10:26:06 GMT
Content-Length: 451

> 2020-02-27T112606-2.200.txt

Response code: 200 (OK); Time: 71ms; Content length: 451 bytes
```

**Comment by Timendus** [comment]
Oh, well looks like it's been fixed then? :) Otherwise your test should have found the issue.

I haven't run into this issue for a while myself. Maybe I'm just not calling these endpoints in this way anymore, or maybe it's just been fixed.

Either way, let's just close this for now.
