### ISSUE TITLE
Decide on certificate validity

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-crypto#19]
What should we do when issuing a certificate that can't live up to the configured validity, since its issuing CA certificate's isn't valid long enough? E.g. the CA certificate is still 6 months valid, but we're issuing a certificate that's meant to be valid for a year.

Normally this isn't allowed (e.g. Logius' PKIOverheid guidelines) and the CA certificate's remaining validity should be at least as long as the certificates' requested validity it issues.

@woutslakhorst?

**Comment by woutslakhorst** [comment]
Let's follow the guidelines. Some thoughts:

- TLS certificates should be short lived, like 2 months max (like let's encrypt does). This would remove the problem for those certs.
- Enable auto-refresh for those certs.
- Certificates for signing/encryption should live for a year
- Meaning that the CA cert for signing/encryption has to be updated when it still has 1 year to go.
- CA for TLS has to be refreshed 2 months before expiry
- Intermediates will be valid for 3 years? And should thus be refreshed after 2 years. (or sooner when their CA expires)
- Root for 5 or 10 years?

**Comment by reinkrul** [comment]
TODO: Add a section to the 'Certificates' chapter of the documentation describing the intended validity periods of the certificates

**Comment by woutslakhorst** [comment]
This is now part of the certificate structure RFC. In general Vendor CA's are valid for a year and others are valid for 4 days.
