### ISSUE TITLE
Use JWE for encrypted data rather than plain RSA-OAEP

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-crypto#43]
We currently used RSA-OAEP to encrypt data which is hardcoded into nuts-crypto. This is a problem when we want to support other schemes or elliptic curve cryptography in the future since we currently don't encode the encryption scheme along with the cipher text, making cipher texts from different schemes indistinguishable from each other.

As such we should encode the used scheme along with the cipher text, preferably in a standardized format. JWE is a very good candidate for it, since it 1. supports EC cryptography and 2. supports multiple recipients with each having their own encrypted content encryption key.

The JWX library we use (lestrrat/jwx) fully supports this.

**Backwards compatibility**
Since directly switching to JWE would break implementations which don't support JWE yet, we can't directly switch to JWE. The upgrade path would be as following:
1. v0.14: add support for encrypting and decrypting using JWE but default to the current format when encrypting data
2. v0.15: default to JWE

**Comment by woutslakhorst** [comment]
Won't fix
